from eispatterns_examples.bank_system.decorators.credit_analyst_decorator import CreditAnalystDecorator
from eispatterns_examples.bank_system.decorators.bank_account_decorator import BankAccountDecorator
from eispatterns_examples.bank_system.decorators.employee_decorator import EmployeeDecorator
from eispatterns_examples.bank_system.resources.loan import Loan
from eispatterns_examples.bank_system.resources.loan_request import LoanRequest

