from bank_system.decorators.credit_analyst_decorator import CreditAnalystDecorator
from bank_system.decorators.bank_account_decorator import BankAccountDecorator
from bank_system.resources.loan import Loan
from bank_system.resources.loan_request import LoanRequest

